
export default [
  {
    id: 52,
    name: 'offre numéro 1',
    disponibility: true,
    type: 'location',
    location: 'Rixheim (68170)',
    coordinates: {
      lat: '47.742939',
      lng: '7.399070',
    },
  },
  {
    id: 5,
    name: 'offre numéro 2',
    disponibility: true,
    type: 'pret',
    location: 'Rixheim (68170)',
    coordinates: {
      lat: '47.742939',
      lng: '7.399070',
    },
  },
  {
    id: 6,
    name: 'offre numéro 3',
    disponibility: false,
    type: 'location',
    location: 'Habsheim (68440)',
    coordinates: {
      lat: '47.728760',
      lng: '7.416620',
    },
  },
  {
    id: 23,
    name: 'offre numéro 4',
    disponibility: true,
    type: 'location',
    location: 'Mulhouse (68100)',
    coordinates: {
      lat: '47.749460',
      lng: '7.339540',
    },
  },
  {
    id: 13,
    name: 'offre numéro 5',
    disponibility: false,
    type: 'location',
    location: 'Saint-Louis (68300)',
    coordinates: {
      lat: '47.589670',
      lng: '7.560080',
    },
  },
  {
    id: 22,
    name: 'offre numéro 6',
    disponibility: true,
    type: 'pret',
    location: 'Mulhouse (68100)',
    coordinates: {
      lat: '47.749460',
      lng: '7.339540',
    },
  },
  {
    id: 69,
    name: 'offre numéro 7',
    disponibility: true,
    type: 'pret',
    location: 'Rixheim (68170)',
    coordinates: {
      lat: '47.742939',
      lng: '7.399070',
    },
  },

];

/*
export default [
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629835',
      street: {
        id: 883303,
        name: 'On or near Parking Area',
      },
      longitude: '-1.133005',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78210733,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629835',
      street: {
        id: 883303,
        name: 'On or near Parking Area',
      },
      longitude: '-1.133005',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78211526,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629797',
      street: {
        id: 883332,
        name: 'On or near Princess Road Backways',
      },
      longitude: '-1.130272',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78212901,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629835',
      street: {
        id: 883303,
        name: 'On or near Parking Area',
      },
      longitude: '-1.133005',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78210990,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629864',
      street: {
        id: 883190,
        name: 'On or near Petrol Station',
      },
      longitude: '-1.115053',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78212909,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.627933',
      street: {
        id: 883416,
        name: 'On or near Parking Area',
      },
      longitude: '-1.139691',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78213734,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.636110',
      street: {
        id: 883290,
        name: 'On or near Humberstone Gate',
      },
      longitude: '-1.131802',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78211800,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.637005',
      street: {
        id: 883354,
        name: 'On or near Kildare Street',
      },
      longitude: '-1.130026',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78211817,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629348',
      street: {
        id: 883343,
        name: 'On or near Museum Square',
      },
      longitude: '-1.129040',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78211818,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.633347',
      street: {
        id: 883387,
        name: 'On or near Berridge Street',
      },
      longitude: '-1.135034',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78210732,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.634369',
      street: {
        id: 883214,
        name: 'On or near Pegasus Close',
      },
      longitude: '-1.117533',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78211824,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629348',
      street: {
        id: 883343,
        name: 'On or near Museum Square',
      },
      longitude: '-1.129040',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78212937,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629835',
      street: {
        id: 883303,
        name: 'On or near Parking Area',
      },
      longitude: '-1.133005',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78213202,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.629835',
      street: {
        id: 883303,
        name: 'On or near Parking Area',
      },
      longitude: '-1.133005',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78212918,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.639138',
      street: {
        id: 883355,
        name: 'On or near Junior Street',
      },
      longitude: '-1.137683',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78212917,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.632887',
      street: {
        id: 883388,
        name: 'On or near Belvoir Street',
      },
      longitude: '-1.131127',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78212915,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.637600',
      street: {
        id: 883324,
        name: 'On or near St Peters Lane',
      },
      longitude: '-1.135171',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78212911,
    location_subtype: '',
    month: '2019-10',
  },
  {
    category: 'anti-social-behaviour',
    location_type: 'Force',
    location: {
      latitude: '52.637414',
      street: {
        id: 883138,
        name: 'On or near Hart Road',
      },
      longitude: '-1.113600',
    },
    context: '',
    outcome_status: null,
    persistent_id: '',
    id: 78217292,
    location_subtype: '',
    month: '2019-10',
  },
];
*/
